### ISSUE TITLE
Nonstandard column names cause problems

### ISSUE THREAD

**Issue by seandavi** [Waller-SUSAN/gateR#1]
When data.frame has names that include characters that are not valid R names, column selection fails. 

- [ ] fix names issue
   - Consider checking for valid names
   - Consider running `make.names` on all names prior to running
- [ ] Add test to catch regressions

**Comment by idblr** [comment]
Added a `make.names()` on `vars` and `colnames(dat)` in the `gating()` function in https://github.com/Waller-SUSAN/gateR/commit/2c3dfcf8dc12d4e22a900d20c8459210f0511a56 before a  check for valid names on L95-100
```
  vars <- make.names(vars, unique = TRUE)
  colnames(dat) <- make.names(colnames(dat), unique = TRUE)
  
  if (!all(vars %in% colnames(dat))) {
    stop("All elements in the argument 'vars' must match named features of 'dat'" )
  }
```
