### ISSUE TITLE
When alpha is too small, cut "doesn't work".

### ISSUE THREAD

**Issue by seandavi** [Waller-SUSAN/gateR#2]

**Comment by idblr** [comment]
Perhaps @SubiNair has a MWE

In https://github.com/Waller-SUSAN/gateR/commit/b2741c8f059363b3412db44eb367e7d428302a91 I changed the 'right' argument in the cut() function within the pval_plot() function back to the default "TRUE" to include the lower bound -Inf value. Lets test if this fixes the issue or if we will see the error on the upper bound Inf now

**Comment by SubiNair** [comment]
Error (version 0.1.6 of gateR package): 

`Error in alpha/2 : non-numeric argument to binary operator
Calls: gating ... <Anonymous> -> <Anonymous> -> .local -> cut -> cut -> cut.default`

The alpha value was 0.001 
Other parameters:

Dataset was full_data_single which is the single condition .RDS that I provided, markers were CD57, CD45, Perforin, CD3 in that order, correlation = none, numerator = TRUE

For testing, the markers would be (In113)Dd, (La139)Dd, Pr141)Dd, (Nd142)Dd

**Comment by idblr** [comment]
I can reproduce the error if you set the 'alpha' parameter in the gating() function as a character value:
```
gating(...,
           alpha = "0.001")
```
but the function works if the 'alpha' argument is numeric:
```
gating(...,
           alpha = 0.001)
```
@SubiNair is the GUI setting this parameter as numeric values for the 'alpha' argument?

**Comment by SubiNair** [comment]
I added an additional line to coerce the value into numeric just in case, this test case works. I am closing the issue.
