### ISSUE TITLE
When using `verbose=TRUE`, `gating()` doesn't output much extra stuff.

### ISSUE THREAD

**Issue by seandavi** [Waller-SUSAN/gateR#3]

**Comment by idblr** [comment]
Removed 'verbose' argument in gating(), lotrrs(), and rrs() functions as it was originally used to troubleshoot the sparr::risk() function. Can be found in https://github.com/Waller-SUSAN/gateR/commit/b2741c8f059363b3412db44eb367e7d428302a91
